name: 'sales_and_marketing_dwh'
version: '1.0'
profile: 'duckdb'

models:
  sales_and_marketing_dwh:
    staging:
      +schema: staging
    core:
      +schema: core
    data_products:
      +schema: data_products