version: 2

sources:
  - name: raw
    description: "Raw data loaded into DuckDB"
    tables:
      - name: sales
        description: "Transactional sales data"
        columns:
          - name: sale_id
            description: "Unique identifier for each sale"
            tests:
              - unique
              - not_null
          - name: product_id
            description: "Identifier for the product sold"
            tests:
              - not_null
          - name: customer_id
            description: "Identifier for the customer"
            tests:
              - not_null
          - name: amount
            description: "Sale amount"
            tests:
              - not_null
          - name: date
            description: "Date of sale"
            tests:
              - not_null
      - name: customers
        description: "Customer information"
        columns:
          - name: customer_id
            description: "Unique identifier for each customer"
            tests:
              - unique
              - not_null
          - name: first_name
            description: "First name of the customer"
            tests:
              - not_null
          - name: last_name
            description: "Last name of the customer"
            tests:
              - not_null
          - name: signup_date
            description: "Signup date of the customer"
            tests:
              - not_null
      - name: marketing_campaigns
        description: "Marketing campaign details"
        columns:
          - name: campaign_id
            description: "Unique identifier for each campaign"
            tests:
              - unique
              - not_null
          - name: channel
            description: "Marketing channel used"
            tests:
              - not_null
          - name: start_date
            description: "Start date of the campaign"
            tests:
              - not_null
          - name: budget
            description: "Budget allocated for the campaign"
            tests:
              - not_null